GlowDash:
  DashboardTitle: "GlowDash"       #Show in main title line (You can change to your home name)
  ReadWindInfo: false                #If true: reads some wind informations and show in title line
  DebugLevel: 0                    # 0 - silent, 1,2,3,4...
  StaticDirectory: "static"        # Location of static glowdash files,js,css, images 
  UserDirectory: "user"            # Location of user images
  StateConfigDirectory: "config"   # Location where the scheduled tasks file is saved
  WebUseSSE: 0                     # 0: disabled, 1: Make the browsers connect to SSE server
  CommUseSSE: 0                    # 0: disabled, 1: Enable the Glowdash notify SSE server
  Panels:                          # You can define panels here
    - Title: Shedule editor
      PanelType: Launch
      Thumbnail: schedules.png
      LaunchTo: schedpage

  Pages:
    - Title: Scheduled tasks
      PageType: ScheduleEdit
      PageName: schedpage
