services:
  glowdash:
    build: .
    restart: unless-stopped
    environment:
      TZ: "Europe/Budapest"
    ports:
      - "80:80"
    volumes:
      - ./userstuff:/glowdash/user
      - ./config:/glowdash/config
