name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment:
      name: prod-to-dockerhub

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.PTDH_DOCKERHUB_USERNAME }}
        password: ${{ secrets.PTDH_DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: hyperprog/glowdash
        tags: |
              type=raw,value=latest

        labels: |
          org.opencontainers.image.title=Glowdash
          org.opencontainers.image.description=The Smart Home Web Dashboard for Raspberry Pi and PC
          org.opencontainers.image.vendor=HyperProg

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        platforms: |
          linux/amd64,
          linux/arm32v6,
          linux/arm32v7,
          linux/arm64v8

        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
